package com.example.jetpackcomposebasic.ui.theme

import androidx.compose.ui.graphics.Color


// # -> 0xFF
// primary color(base color)=#19753a
val android_light_primary = Color(0xFF0b6d33)
val android_light_onPrimary = Color(0xFFffffff)
val android_light_primaryContainer = Color(0xFF9df6ad)
val android_light_onPrimaryContainer = Color(0xFF00210a)
val android_light_secondary = Color(0xFF506351)
val android_light_onSecondary = Color(0xFFffffff)
val android_light_secondaryContainer = Color(0xFFd3e8d2)
val android_light_onSecondaryContainer = Color(0xFF0e1f11)
val android_light_tertiary = Color(0xFF39656d)
val android_light_onTertiary = Color(0xFFffffff)
val android_light_tertiaryContainer = Color(0xFFbdeaf4)
val android_light_onTertiaryContainer = Color(0xFF001f25)
val android_light_error = Color(0xFFba1a1a)
val android_light_onError = Color(0xFFffffff)
val android_light_errorContainer = Color(0xFFffdad6)
val android_light_onErrorContainer = Color(0xFF410002)
val android_light_background = Color(0xFFfcfdf7)
val android_light_onBackground = Color(0xFF1a1c19)
val android_light_surface = Color(0xFFfcfdf7)
val android_light_onSurface = Color(0xFF1a1c19)
val android_light_surfaceVariant = Color(0xFFdde5da)
val android_light_onSurfaceVariant = Color(0xFF414941)
val android_light_outline = Color(0xFF727970)
val android_light_inverseOnSurface = Color(0xFFF9EFE7)
val android_light_inverseSurface = Color(0xFF34302A)
val android_light_inversePrimary = Color(0xFFFFB951)
val android_light_shadow = Color(0xFF000000)
val android_light_surfaceTint = Color(0xFF825500)
val android_light_outlineVariant = Color(0xFFD3C4B4)
val android_light_scrim = Color(0xFF000000)

val android_dark_primary = Color(0xFF82d993)
val android_dark_onPrimary = Color(0xFF003917)
val android_dark_primaryContainer = Color(0xFF005224)
val android_dark_onPrimaryContainer = Color(0xFF9df6ad)
val android_dark_secondary = Color(0xFFb7ccb6)
val android_dark_onSecondary = Color(0xFF233425)
val android_dark_secondaryContainer = Color(0xFF394b3b)
val android_dark_onSecondaryContainer = Color(0xFFd3e8d2)
val android_dark_tertiary = Color(0xFFa1ced8)
val android_dark_onTertiary = Color(0xFF00363e)
val android_dark_tertiaryContainer = Color(0xFF204d55)
val android_dark_onTertiaryContainer = Color(0xFFbdeaf4)
val android_dark_error = Color(0xFFffb4ab)
val android_dark_onError = Color(0xFF690005)
val android_dark_errorContainer = Color(0xFF93000a)
val android_dark_onErrorContainer = Color(0xFFffdad6)
val android_dark_background = Color(0xFF1a1c19)
val android_dark_onBackground = Color(0xFFe2e3de)
val android_dark_surface = Color(0xFF1a1c19)
val android_dark_onSurface = Color(0xFFe2e3de)
val android_dark_surfaceVariant = Color(0xFF414941)
val android_dark_onSurfaceVariant = Color(0xFFc1c9be)
val android_dark_outline = Color(0xFF8b9389)
val android_dark_inverseOnSurface = Color(0xFF1F1B16)
val android_dark_inverseSurface = Color(0xFFEAE1D9)
val android_dark_inversePrimary = Color(0xFF825500)
val android_dark_shadow = Color(0xFF000000)
val android_dark_surfaceTint = Color(0xFFFFB951)
val android_dark_outlineVariant = Color(0xFF4F4539)
val android_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF825500)
